### ISSUE TITLE
Wizard/Seeker login

### ISSUE THREAD

**Issue by ceemion** [SundayAdefila/cGuides#29]
When I logged in a seeker info in the wizard form, it goes through!
Apparently, there is no check to see if the person is a wizard or seeker when checking for the profile in sessions controller. @SundayAdefila

**Comment by SundayAdefila** [comment]
@ceemion  The reason we had diff sign_in path before was because we were trying to make the sign_in through google create new account for newcommers. but since we are removing that, and just forcing them to fill the form, only helping in prefilling some, I'm  thinking of having only one endpoint. what do you think?

**Comment by ceemion** [comment]
@SundayAdefila With one endpoint, we would still need a way to know if it's a seeker or wizard on login. How do you propose we attack this?

**Comment by SundayAdefila** [comment]
Hope this is clear now?

**Comment by ceemion** [comment]
Yea
